/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_AHB1ENR ((volatile uint32_t*)0x40023830)
#define GPIOA_MODER ((volatile uint32_t*)0x40020000)
#define GPIOA_ODR ((volatile uint32_t*)0x40020014)

void delay(volatile uint32_t count) {
    while (count--);
}
int main(void){
     *RCC_AHB1ENR |= (1<<0);
     *GPIOA_MODER &= ~(3<<10);
     *GPIOA_MODER |= (1<<10);
     while(1){
          *GPIOA_ODR ^= (1<<5);
          delay(500000);
                       }
                               }

