/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include <stdint.h>

#define GPIOA_MODER     ((volatile uint32_t*)0x40020000)
#define RCC_AHB1ENR     ((volatile uint32_t*)0x40023830)
#define GPIOA_ODR       ((volatile uint32_t*)0x40020014)
#define RCC_APB2ENR     ((volatile uint32_t*)0x40023844)
#define SYSCFG_EXTICR4  ((volatile uint32_t*)0x40013814)
#define NVIC_ISER1      ((volatile uint32_t*)0xE000E104)
#define EXTI_PR         ((volatile uint32_t*)0x40013C14)
#define GPIOC_PUPDR     ((volatile uint32_t*)0x4002080C)
#define EXTI_IMR        ((volatile uint32_t*)0x40013C00)
#define EXTI_FTSR       ((volatile uint32_t*)0x40013C0C)

void EXTI15_10_IRQHandler(void) {

    *GPIOA_ODR ^= (1 << 5);   // Invierte el estado del LED en PA5
    *EXTI_PR   |= (1 << 13);  // Limpia el flag de interrupción pendiente de EXTI13 — sin esto la ISR se repetiría en bucle
}

int main(void) {

    *RCC_AHB1ENR |= (1 << 0);  // Habilita el clock de GPIOA — necesario para controlar el LED en PA5
    *RCC_AHB1ENR |= (1 << 2);  // Habilita el clock de GPIOC — necesario para leer el pulsador en PC13
    *RCC_APB2ENR |= (1 << 14); // Habilita el clock del SYSCFG — necesario para conectar PC13 a la línea EXTI13

    *GPIOC_PUPDR &= ~(3 << 26); // Limpia los bits 27:26 de PUPDR — borra cualquier valor previo en PC13
    *GPIOC_PUPDR |=  (1 << 26); // Configura pull-up interno en PC13 — mantiene el pin en nivel alto cuando el pulsador no está presionado

    *GPIOA_MODER &= ~(3 << 10); // Limpia los bits 11:10 de MODER — borra cualquier valor previo en PA5
    *GPIOA_MODER |=  (1 << 10); // Configura PA5 como salida digital (valor 01 en bits 11:10)

    *SYSCFG_EXTICR4 &= ~(15 << 4); // Limpia los bits 7:4 — borra la selección de puerto previa para EXTI13
    *SYSCFG_EXTICR4 |=  (2 << 4);  // Conecta el puerto C a la línea EXTI13 (valor 0010 = puerto C)

    *EXTI_FTSR |= (1 << 13); // Habilita detección de flanco de bajada en EXTI13 — el pulsador genera 1→0 al presionarse
    *EXTI_IMR  |= (1 << 13); // Desenmascara la línea EXTI13 — sin esto el EXTI bloquea la señal y no llega al NVIC
    *NVIC_ISER1 |= (1 << 8); // Habilita IRQ40 en el NVIC — autoriza al CPU a ejecutar la ISR cuando llegue la interrupción

    while (1) {} // Bucle infinito vacío — el programa espera interrupciones del pulsador
}
